require: rubocop-rspec

inherit_gem:
  fashion_police:
    - default.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - spec/dummy/db/schema.rb

RSpec/FilePath:
  Enabled: false

Layout/LineLength:
  Exclude:
    - spec/dummy/db/schema.rb
    - bin/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
