default: &default
  adapter:  mysql2
  pool:     5
  username:
  password:
  host:     127.0.0.1
  port:     3306

development:
  <<: *default
  database: subscriptions_broker_development

test:
  <<: *default
  database: subscriptions_broker_test

production:
  <<: *default
  database: subscriptions_broker_production
