default: &default
  adapter:  postgresql
  pool: 5
  username:
  password:
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: broadcaster_development

test:
  <<: *default
  database: broadcaster_test

production:
  <<: *default
  database: broadcaster_production
