version: 2

workflows:
  version: 2

  test_and_review:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - test_rails:
          requires:
            - build
      - review:
          requires:
            - build

  test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test_rails:
          requires:
            - build

jobs:
  build:
    working_directory: ~/KissKissBankBank/broadcaster
    docker:
      - &default_image
        image: circleci/ruby:2.6-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: root
      - &postgresql_image
        image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password

    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - broadcaster-bundle-{{ checksum "Gemfile" }}-{{ checksum "broadcaster.gemspec" }}
            - broadcaster-bundle-
      - run: sudo apt-get update
      - run: sudo apt install -y cmake libssh-dev
      - run: sudo apt install postgresql-client
      - run: bundle check || bundle install
      - save_cache:
          key: broadcaster-bundle-{{ checksum "Gemfile" }}-{{ checksum "broadcaster.gemspec" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

  test_rails:
    docker:
      - *default_image
      - *postgresql_image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - run: bundle exec rake app:db:create app:db:migrate
      - run: bin/circle/test-rails
      - store_test_results:
          path: ~/rspec

  review:
    docker:
      - *default_image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: bin/circle/review
